rose_planner_node:
  ros__parameters:
    odom_topic: /Odometry
    goal_topic: /rose_goal
    robot_size: [0.3, 0.3]
    path_search:
      a_star: 
        clearance_weight: 2.0
        obstacle_penalty_weight: 10.0
        heuristic_weight: 1.0
      resampler:
        max_vel: 3.0
        acc: 2.0
        dt: 0.1
    trajectory_opt:
      smooth_weight: 1.0
      obstacle_weight: 0.9
    rose_map:
      log_time: true
      pointcloud_topic: /cloud_registered
      sensor_frame: front_mid360
      max_update_rate: 10
      occ_map:
        origin: [0.0, 0.0, 0.0]
        size: [17.0, 17.0, 1.0]
        voxel_size: 0.02
        log_hit: 0.85
        log_free: -0.3
        log_min: -5.0
        log_max: 10.0
        occ_th: 0.0       
        min_shift: 2
        timeout: 1.5
        unknown_is_occupied: false
        use_ray: true
        max_ray_range: 20.0
      acc_map:
        origin: [0.0, 0.0]
        size: [12.0, 12.0]
        voxel_size: 0.05
        origin2base: 0.2
        min_diff_z: 0.1
        min_block_count: 2
        block_ratio: 0.15
        kernel_size: 3
        dilate_iter: 1
        use_static_map: true
        static_map_path: "/home/hy/wust_nav2/src/bringup_nav/map/simulation/rmuc_2026.yaml"
      esdf:
        use_diagonals: true